#ifndef INC_SYSTEM_DATABASE
#define INC_SYSTEM_DATABASE

#ifdef __cplusplus
extern "C" {
#endif

#include <actor/actor.h>
#include "sqlite_config.h"
#include "sqlite3.h"

/* Start of autogenerated OD types */
/* 0x6080: Actor Database
   SQLite instance */
typedef struct actor_database_properties {
    uint8_t parameter_count;
    int16_t storage_index;
    uint32_t journal_buffer_size;
    char path[11];
    uint8_t phase;
} actor_database_properties_t;
/* End of autogenerated OD types */



struct actor_database {
    actor_t *actor;
    actor_database_properties_t *properties;

    actor_thread_t *thread;
    actor_worker_t worker;
    actor_job_t *job;

    actor_generic_device_t *storage;
    actor_buffer_t *journal_buffer;
    
    sqlite3 *connection;
    sqlite3_vfs vfs;
    sqlite3_io_methods vfs_io;
};


extern actor_interface_t actor_database_class;



#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif