#ifndef INC_DEV_BLANK
#define INC_DEV_BLANK

#ifdef __cplusplus
extern "C" {
#endif

#include <actor/actor.h>


/* Start of autogenerated OD types */
/* 0x9100: Screen ILI9341null */
typedef struct screen_ili9341_properties {
    uint8_t parameter_count;
    int16_t width;
    uint16_t height;
    uint8_t phase;
    uint8_t orientation;
    bool_t invert_colors;
    bool_t backlight;
} screen_ili9341_properties_t;
/* End of autogenerated OD types */

struct screen_ili9341 {
    actor_t *actor;
    actor_job_t *job;
    uint16_t *cmd_register;
    uint16_t *data_register;
    screen_ili9341_properties_t *properties;
    actor_mutex_t *sleep_mutex;
    uint32_t sleep_mutex_expiration_time;
};

// https://cdn-shop.adafruit.com/datasheets/ILI9341.pdf
enum screen_ili9341_cmd {
    ILI9341_CMD_POWER_CONTROL_B = 0xCF,
    ILI9341_CMD_POWER_SEQUENCE_CONTROL = 0xED,
    ILI9341_CMD_DRIVER_TIMING_CONTROL_A = 0xE8,
    ILI9341_CMD_DRIVER_TIMING_CONTROL_B = 0xEA,
    ILI9341_CMD_POWER_CONTROL_A = 0xCB,
    ILI9341_CMD_POWER_CONTROL_1 = 0xC0,
    ILI9341_CMD_POWER_CONTROL_2 = 0xC1,
    ILI9341_CMD_PUMP_RATIO_CONTROL = 0xF7,
    ILI9341_CMD_VCOM_CONTROL_1 = 0xC5,
    ILI9341_CMD_VCOM_CONTROL_2 = 0xC7,
    ILI9341_CMD_MEMORY_CONTROL = 0x36,
    ILI9341_CMD_PIXEL_FORMAT_SET = 0x3A,
    ILI9341_CMD_FRAME_RATE_CONTROL_NORMAL = 0xB1,
    ILI9341_CMD_DISPLAY_FUNCTION_CONTROL = 0xB6,
    ILI9341_CMD_ENABLE_3g = 0xF2, 
    ILI9341_CMD_GAMMA_SET = 0x26,
    ILI9341_CMD_POSITIVE_GAMMA_CORRECTION = 0xE0, 
    ILI9341_CMD_NEGATIVE_GAMMA_CORRECTION = 0XE1,
    ILI9341_CMD_PAGE_ADDRESS_SET = 0x2B,
    ILI9341_CMD_COLUMN_ADDRESS_SET = 0x2A,
    ILI9341_CMD_SLEEP_OUT = 0x11,
    ILI9341_CMD_SLEEP_IN = 0x10,
    ILI9341_CMD_DISPLAY_OFF = 0x28,
    ILI9341_CMD_DISPLAY_ON = 0x29,
    ILI9341_CMD_INVERT_COLORS_OFF = 0x20,
    ILI9341_CMD_INVERT_COLORS_ON = 0x21,
};


extern actor_interface_t screen_ili9341_class;



#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif