#ifndef INC_SYSTEM_DATABASE
#define INC_SYSTEM_DATABASE

#ifdef __cplusplus
extern "C" {
#endif

#include "core/actor.h"
#include "sqlite_config.h"
#include "sqlite3.h"

/* Start of autogenerated OD types */
/* 0x6080: System Database
   SQLite instance */
typedef struct system_database_properties {
    uint8_t parameter_count;
    int16_t storage_index;
    uint32_t journal_buffer_size;
    char path[11];
    uint8_t phase;
} system_database_properties_t;
/* End of autogenerated OD types */

struct system_database {
    actor_t *actor;
    system_database_properties_t *properties;

    app_thread_t *thread;
    actor_worker_t worker;
    app_job_t *job;

    app_generic_device_t *storage;
    app_buffer_t *journal_buffer;
    
    sqlite3 *connection;
    sqlite3_vfs vfs;
    sqlite3_io_methods vfs_io;
};


extern actor_class_t system_database_class;

/* Start of autogenerated OD accessors */
typedef enum system_database_properties_indecies {
  SYSTEM_DATABASE_STORAGE_INDEX = 0x01,
  SYSTEM_DATABASE_JOURNAL_BUFFER_SIZE = 0x02,
  SYSTEM_DATABASE_PATH = 0x03,
  SYSTEM_DATABASE_PHASE = 0x04
} system_database_properties_indecies_t;

/* 0x60XX04: undefined */
static inline void system_database_set_phase(system_database_t *database, uint8_t value) { 
    actor_set_property_numeric(database->actor, SYSTEM_DATABASE_PHASE, (uint32_t)(value), sizeof(uint8_t));
}
static inline uint8_t system_database_get_phase(system_database_t *database) {
    return *((uint8_t *) actor_get_property_pointer(database->actor, SYSTEM_DATABASE_PHASE));
}
/* End of autogenerated OD accessors */

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif