#ifndef INC_STORAGE_AT24C
#define INC_STORAGE_AT24C

#ifdef __cplusplus
extern "C" {
#endif

#include "actor.h"

/* Start of autogenerated OD types */
/* 0x7400: Storage AT24C
   I2C-based EEPROM */
typedef struct storage_at24c_properties {
    uint8_t parameter_count;
    uint16_t i2c_index;
    uint8_t i2c_address;
    uint16_t start_address;
    uint16_t page_size;
    uint16_t size;
    uint8_t phase;
} storage_at24c_properties_t;
/* End of autogenerated OD types */

struct storage_at24c {
    actor_t *actor;
    storage_at24c_properties_t *properties;
    transport_i2c_t *i2c;
    actor_job_t *job;
    actor_buffer_t *source_buffer;
    actor_buffer_t *target_buffer;
};

extern actor_class_t storage_at24c_class;

/* Start of autogenerated OD accessors */
typedef enum storage_at24c_properties_indecies {
  STORAGE_AT24C_I2C_INDEX = 0x01,
  STORAGE_AT24C_I2C_ADDRESS = 0x02,
  STORAGE_AT24C_START_ADDRESS = 0x03,
  STORAGE_AT24C_PAGE_SIZE = 0x04,
  STORAGE_AT24C_SIZE = 0x05,
  STORAGE_AT24C_PHASE = 0x06
} storage_at24c_properties_indecies_t;

/* 0x74XX06: null */
static inline void storage_at24c_set_phase(storage_at24c_t *at24c, uint8_t value) { 
    actor_set_property_numeric(at24c->actor, STORAGE_AT24C_PHASE, (uint32_t)(value), sizeof(uint8_t));
}
static inline uint8_t storage_at24c_get_phase(storage_at24c_t *at24c) {
    return *((uint8_t *) actor_get_property_pointer(at24c->actor, STORAGE_AT24C_PHASE));
}
/* End of autogenerated OD accessors */

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif