#ifndef INC_DEV_BLANK
#define INC_DEV_BLANK

#ifdef __cplusplus
extern "C" {
#endif

#include <actor/actor.h>

/* Start of autogenerated OD types */
/* 0x9100: ILI9341null */
typedef struct screen_ili9341_properties {
    uint8_t parameter_count;
    uint32_t sub_object1;
    uint8_t phase;
} screen_ili9341_properties_t;
/* End of autogenerated OD types */


struct actor_blank {
    actor_t *actor;
    actor_blank_properties_t *properties;
};


extern actor_interface_t actor_blank_class;



#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif