#ifndef INC_DEV_BLANK
#define INC_DEV_BLANK

#ifdef __cplusplus
extern "C" {
#endif

#include <actor/actor.h>

/* Start of autogenerated OD types */
/* 0x9800: Indicator LED 1null */
typedef struct indicator_led_properties {
    uint8_t parameter_count;
    uint8_t port;
    uint8_t pin;
    uint8_t phase; // Current state of a device (DEVICE_PHASE) 
    uint8_t duty_cycle; // Brightness of LED between 0 and 255 
} indicator_led_properties_t;
/* End of autogenerated OD types */

struct indicator_led {
    actor_t *actor;
    indicator_led_properties_t *properties;
};


extern actor_interface_t indicator_led_class;



#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif