#ifndef INC_ENUMS
#define INC_ENUMS
#include <stdint.h>
// defined in ./lib/actor_cm3/src/actor/transport/modbus.h
char* get_transport_modbus_cmd_name (uint32_t v);
// defined in ./lib/actor_drivers/src/actor/storage/w25.h
char* get_w25_commands_name (uint32_t v);
// defined in ./lib/actor_node/src/actor/actor.h
char* get_actor_phase_name (uint32_t v);
// defined in ./lib/actor_rtos/src/actor/buffer.h
char* get_actor_buffer_flag_name (uint32_t v);
// defined in ./lib/actor_rtos/src/actor/event.h
char* get_actor_event_type_name (uint32_t v);
// defined in ./lib/actor_rtos/src/actor/event.h
char* get_actor_event_status_name (uint32_t v);
// defined in ./lib/actor_rtos/src/actor/event.h
char* get_actor_signal_name (uint32_t v);
// defined in ./lib/actor_rtos/src/actor/file.h
char* get_actor_file_mode_name (uint32_t v);
// defined in ./lib/actor_rtos/src/actor/job.h
char* get_actor_job_signal_name (uint32_t v);
// defined in ./lib/actor_rtos/src/actor/thread.h
char* get_actor_thread_flags_name (uint32_t v);
// defined in ./src/definitions/accessors.h
char* get_device_circuit_properties_indecies_name (uint32_t v);
// defined in ./src/definitions/accessors.h
char* get_module_mcu_properties_indecies_name (uint32_t v);
// defined in ./src/definitions/accessors.h
char* get_actor_canopen_properties_indecies_name (uint32_t v);
// defined in ./src/definitions/accessors.h
char* get_actor_database_properties_indecies_name (uint32_t v);
// defined in ./src/definitions/accessors.h
char* get_module_timer_properties_indecies_name (uint32_t v);
// defined in ./src/definitions/accessors.h
char* get_transport_can_properties_indecies_name (uint32_t v);
// defined in ./src/definitions/accessors.h
char* get_transport_spi_properties_indecies_name (uint32_t v);
// defined in ./src/definitions/accessors.h
char* get_transport_usart_properties_indecies_name (uint32_t v);
// defined in ./src/definitions/accessors.h
char* get_transport_i2c_properties_indecies_name (uint32_t v);
// defined in ./src/definitions/accessors.h
char* get_transport_modbus_properties_indecies_name (uint32_t v);
// defined in ./src/definitions/accessors.h
char* get_transport_sdio_properties_indecies_name (uint32_t v);
// defined in ./src/definitions/accessors.h
char* get_module_adc_properties_indecies_name (uint32_t v);
// defined in ./src/definitions/accessors.h
char* get_storage_eeprom_properties_indecies_name (uint32_t v);
// defined in ./src/definitions/accessors.h
char* get_storage_w25_properties_indecies_name (uint32_t v);
// defined in ./src/definitions/accessors.h
char* get_storage_flash_properties_indecies_name (uint32_t v);
// defined in ./src/definitions/accessors.h
char* get_memory_sram_properties_indecies_name (uint32_t v);
// defined in ./src/definitions/accessors.h
char* get_storage_at24c_properties_indecies_name (uint32_t v);
// defined in ./src/definitions/accessors.h
char* get_storage_sdcard_properties_indecies_name (uint32_t v);
// defined in ./src/definitions/accessors.h
char* get_input_sensor_properties_indecies_name (uint32_t v);
// defined in ./src/definitions/accessors.h
char* get_control_touchscreen_properties_indecies_name (uint32_t v);
// defined in ./src/definitions/accessors.h
char* get_screen_epaper_properties_indecies_name (uint32_t v);
// defined in ./src/definitions/accessors.h
char* get_actor_node_properties_indecies_name (uint32_t v);
// defined in ./src/definitions/accessors.h
char* get_indicator_led_properties_indecies_name (uint32_t v);
// defined in ./src/definitions/accessors.h
char* get_signal_beeper_properties_indecies_name (uint32_t v);
// defined in ./src/definitions/dictionary.h
char* get_actor_type_name (uint32_t v);
#endif