#ifndef INC_STORAGE_AT24C
#define INC_STORAGE_AT24C

#ifdef __cplusplus
extern "C" {
#endif

#include "core/actor.h"

/* Start of autogenerated OD types */
/* 0x7400: Storage AT24C
   I2C-based EEPROM */
typedef struct storage_at24c_properties {
    uint8_t parameter_count;
    uint16_t i2c_index;
    uint8_t i2c_address;
    uint16_t start_address;
    uint16_t page_size;
    uint16_t size;
    uint8_t phase;
} storage_at24c_properties_t;
/* End of autogenerated OD types */

struct storage_at24c {
    actor_t *actor;
    storage_at24c_properties_t *properties;
    transport_i2c_t *i2c;
    app_task_t task;
};

extern actor_class_t storage_at24c_class;

/* Start of autogenerated OD accessors */
typedef enum storage_at24c_properties_properties {
  STORAGE_AT24C_I2C_INDEX = 0x01,
  STORAGE_AT24C_I2C_ADDRESS = 0x02,
  STORAGE_AT24C_START_ADDRESS = 0x03,
  STORAGE_AT24C_PAGE_SIZE = 0x04,
  STORAGE_AT24C_SIZE = 0x05,
  STORAGE_AT24C_PHASE = 0x06
} storage_at24c_properties_properties_t;

/* 0x74XX06: null */
#define storage_at24c_set_phase(at24c, value) actor_set_property_numeric(at24c->actor, (uint32_t) value, sizeof(uint8_t), STORAGE_AT24C_PHASE)
#define storage_at24c_get_phase(at24c) *((uint8_t *) actor_get_property_pointer(at24c->actor, &(uint8_t[sizeof(uint8_t)]{}), sizeof(uint8_t), STORAGE_AT24C_PHASE)
/* End of autogenerated OD accessors */

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif