#ifndef INC_STORAGE_SDCARD
#define INC_DEV_BLANK

#ifdef __cplusplus
extern "C" {
#endif

#include "core/actor.h"

/* Start of autogenerated OD types */
/* 0x7500: undefinedundefined */
typedef struct storage_sdcard_properties {
    uint8_t parameter_count;
    uint16_t sdio_index;
    uint8_t phase;
    uint32_t capacity;
    uint32_t block_size;
    uint32_t block_count;
    uint32_t max_bus_clock_frequency;
    uint8_t csd_version;
    uint16_t relative_card_address;
    uint8_t manufacturer_id;
    uint16_t oem_id;
    char product_name[6];
    uint8_t product_revision;
    uint32_t serial_number;
    uint16_t manufacturing_date;
    uint8_t version;
    bool_t high_capacity;
} storage_sdcard_properties_t;
/* End of autogenerated OD types */

struct storage_sdcard {
    actor_t *actor;
    storage_sdcard_properties_t *properties;
};


extern actor_class_t storage_sdcard_class;

/* Start of autogenerated OD accessors */
typedef enum storage_sdcard_properties_properties {
  STORAGE_SDCARD_SDIO_INDEX = 0x01,
  STORAGE_SDCARD_PHASE = 0x02,
  STORAGE_SDCARD_CAPACITY = 0x03,
  STORAGE_SDCARD_BLOCK_SIZE = 0x04,
  STORAGE_SDCARD_BLOCK_COUNT = 0x05,
  STORAGE_SDCARD_MAX_BUS_CLOCK_FREQUENCY = 0x06,
  STORAGE_SDCARD_CSD_VERSION = 0x07,
  STORAGE_SDCARD_RELATIVE_CARD_ADDRESS = 0x08,
  STORAGE_SDCARD_MANUFACTURER_ID = 0x09,
  STORAGE_SDCARD_OEM_ID = 0x0A,
  STORAGE_SDCARD_PRODUCT_NAME = 0x0B,
  STORAGE_SDCARD_PRODUCT_REVISION = 0x0C,
  STORAGE_SDCARD_SERIAL_NUMBER = 0x0D,
  STORAGE_SDCARD_MANUFACTURING_DATE = 0x0E,
  STORAGE_SDCARD_VERSION = 0x0F,
  STORAGE_SDCARD_HIGH_CAPACITY = 0x10
} storage_sdcard_properties_properties_t;

/* 0x75XX02: undefined */
#define storage_sdcard_set_phase(sdcard, value) actor_set_property_numeric(sdcard->actor, STORAGE_SDCARD_PHASE, (uint32_t) (value), sizeof(uint8_t))
#define storage_sdcard_get_phase(sdcard) *((uint8_t *) actor_get_property_pointer(sdcard->actor, STORAGE_SDCARD_PHASE)
/* 0x75XX03: undefined */
#define storage_sdcard_set_capacity(sdcard, value) actor_set_property_numeric(sdcard->actor, STORAGE_SDCARD_CAPACITY, (uint32_t) (value), sizeof(uint32_t))
#define storage_sdcard_get_capacity(sdcard) *((uint32_t *) actor_get_property_pointer(sdcard->actor, STORAGE_SDCARD_CAPACITY)
/* 0x75XX04: undefined */
#define storage_sdcard_set_block_size(sdcard, value) actor_set_property_numeric(sdcard->actor, STORAGE_SDCARD_BLOCK_SIZE, (uint32_t) (value), sizeof(uint32_t))
#define storage_sdcard_get_block_size(sdcard) *((uint32_t *) actor_get_property_pointer(sdcard->actor, STORAGE_SDCARD_BLOCK_SIZE)
/* 0x75XX05: undefined */
#define storage_sdcard_set_block_count(sdcard, value) actor_set_property_numeric(sdcard->actor, STORAGE_SDCARD_BLOCK_COUNT, (uint32_t) (value), sizeof(uint32_t))
#define storage_sdcard_get_block_count(sdcard) *((uint32_t *) actor_get_property_pointer(sdcard->actor, STORAGE_SDCARD_BLOCK_COUNT)
/* 0x75XX06: undefined */
#define storage_sdcard_set_max_bus_clock_frequency(sdcard, value) actor_set_property_numeric(sdcard->actor, STORAGE_SDCARD_MAX_BUS_CLOCK_FREQUENCY, (uint32_t) (value), sizeof(uint32_t))
#define storage_sdcard_get_max_bus_clock_frequency(sdcard) *((uint32_t *) actor_get_property_pointer(sdcard->actor, STORAGE_SDCARD_MAX_BUS_CLOCK_FREQUENCY)
/* 0x75XX07: undefined */
#define storage_sdcard_set_csd_version(sdcard, value) actor_set_property_numeric(sdcard->actor, STORAGE_SDCARD_CSD_VERSION, (uint32_t) (value), sizeof(uint8_t))
#define storage_sdcard_get_csd_version(sdcard) *((uint8_t *) actor_get_property_pointer(sdcard->actor, STORAGE_SDCARD_CSD_VERSION)
/* 0x75XX08: undefined */
#define storage_sdcard_set_relative_card_address(sdcard, value) actor_set_property_numeric(sdcard->actor, STORAGE_SDCARD_RELATIVE_CARD_ADDRESS, (uint32_t) (value), sizeof(uint16_t))
#define storage_sdcard_get_relative_card_address(sdcard) *((uint16_t *) actor_get_property_pointer(sdcard->actor, STORAGE_SDCARD_RELATIVE_CARD_ADDRESS)
/* 0x75XX09: undefined */
#define storage_sdcard_set_manufacturer_id(sdcard, value) actor_set_property_numeric(sdcard->actor, STORAGE_SDCARD_MANUFACTURER_ID, (uint32_t) (value), sizeof(uint8_t))
#define storage_sdcard_get_manufacturer_id(sdcard) *((uint8_t *) actor_get_property_pointer(sdcard->actor, STORAGE_SDCARD_MANUFACTURER_ID)
/* 0x75XX0A: undefined */
#define storage_sdcard_set_oem_id(sdcard, value) actor_set_property_numeric(sdcard->actor, STORAGE_SDCARD_OEM_ID, (uint32_t) (value), sizeof(uint16_t))
#define storage_sdcard_get_oem_id(sdcard) *((uint16_t *) actor_get_property_pointer(sdcard->actor, STORAGE_SDCARD_OEM_ID)
/* 0x75XX0B: undefined */
#define storage_sdcard_set_product_name(sdcard, value, size) actor_set_property_string(sdcard->actor, STORAGE_SDCARD_PRODUCT_NAME, value, size)
#define storage_sdcard_get_product_name(sdcard) *((char *) actor_get_property_pointer(sdcard->actor, STORAGE_SDCARD_PRODUCT_NAME)
/* 0x75XX0C: undefined */
#define storage_sdcard_set_product_revision(sdcard, value) actor_set_property_numeric(sdcard->actor, STORAGE_SDCARD_PRODUCT_REVISION, (uint32_t) (value), sizeof(uint8_t))
#define storage_sdcard_get_product_revision(sdcard) *((uint8_t *) actor_get_property_pointer(sdcard->actor, STORAGE_SDCARD_PRODUCT_REVISION)
/* 0x75XX0D: undefined */
#define storage_sdcard_set_serial_number(sdcard, value) actor_set_property_numeric(sdcard->actor, STORAGE_SDCARD_SERIAL_NUMBER, (uint32_t) (value), sizeof(uint32_t))
#define storage_sdcard_get_serial_number(sdcard) *((uint32_t *) actor_get_property_pointer(sdcard->actor, STORAGE_SDCARD_SERIAL_NUMBER)
/* 0x75XX0E: undefined */
#define storage_sdcard_set_manufacturing_date(sdcard, value) actor_set_property_numeric(sdcard->actor, STORAGE_SDCARD_MANUFACTURING_DATE, (uint32_t) (value), sizeof(uint16_t))
#define storage_sdcard_get_manufacturing_date(sdcard) *((uint16_t *) actor_get_property_pointer(sdcard->actor, STORAGE_SDCARD_MANUFACTURING_DATE)
/* 0x75XX0F: undefined */
#define storage_sdcard_set_version(sdcard, value) actor_set_property_numeric(sdcard->actor, STORAGE_SDCARD_VERSION, (uint32_t) (value), sizeof(uint8_t))
#define storage_sdcard_get_version(sdcard) *((uint8_t *) actor_get_property_pointer(sdcard->actor, STORAGE_SDCARD_VERSION)
/* 0x75XX10: undefined */
#define storage_sdcard_set_high_capacity(sdcard, value) actor_set_property_numeric(sdcard->actor, STORAGE_SDCARD_HIGH_CAPACITY, (uint32_t) (value), sizeof(bool_t))
#define storage_sdcard_get_high_capacity(sdcard) *((bool_t *) actor_get_property_pointer(sdcard->actor, STORAGE_SDCARD_HIGH_CAPACITY)
/* End of autogenerated OD accessors */

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif