#ifndef INC_TRANSPORT_SDIO
#define INC_TRANSPORT_SDIO

#ifdef __cplusplus
extern "C" {
#endif

#include "core/actor.h"
#define SDIO_UNITS 1

#define SDIO_ICR_CMD (SDIO_STA_CCRCFAIL | SDIO_ICR_CTIMEOUTC | SDIO_ICR_CMDRENDC | SDIO_ICR_CMDSENTC)
#define SDIO_ICR_DATA (SDMMC_ICR_RXOVERRC | SDMMC_ICR_DCRCFAILC | SDMMC_ICR_DTIMEOUTC | SDMMC_ICR_DBCKENDC | SDMMC_ICR_STBITERRC)
#define SDIO_ICR_STATIC                                                                                                                    \
    (SDIO_ICR_CCRCFAILC | SDIO_ICR_DCRCFAILC | SDIO_ICR_CTIMEOUTC | SDIO_ICR_DTIMEOUTC | SDIO_ICR_TXUNDERRC | SDIO_ICR_RXOVERRC |          \
     SDIO_ICR_CMDRENDC | SDIO_ICR_CMDSENTC | SDIO_ICR_DATAENDC | SDIO_ICR_DBCKENDC)

#define SDIO_HIGH_CAPACITY ((uint32_t)0x40000000U)
#define SDIO_STANDARD_CAPACITY ((uint32_t)0x00000000U)
#define SDIO_3_0_to_3_3_V ((uint32_t)0x80100000U) // Timeout for CMD0 or CMD8
#define SD_CMD_TIMEOUT ((uint32_t)0x00010000U)

#define SDIO_CLKCR_CLKDIV_TRANSFER 0

// SDIO timeout for data transfer ((48MHz / CLKDIV / 1000) * timeout_ms)
// TODO: Freq
#define SD_DATA_READ_TIMEOUT ((uint32_t)((48000000U / (SDIO_CLKCR_CLKDIV_TRANSFER + 2U) / 1000U) * 100U))  // Data read timeout is 100ms
#define SD_DATA_WRITE_TIMEOUT ((uint32_t)((48000000U / (SDIO_CLKCR_CLKDIV_TRANSFER + 2U) / 1000U) * 250U)) // Date write timeout is 250ms

/* Start of autogenerated OD types */
/* 0x62A0: null
   Secure input/output protocol */
typedef struct transport_sdio_properties {
    uint8_t parameter_count;
    uint8_t dma_unit;
    uint8_t dma_stream;
    uint8_t dma_channel;
    uint8_t af;
    uint8_t d0_port;
    uint8_t d0_pin;
    uint8_t d1_port;
    uint8_t d1_pin;
    uint8_t d2_port;
    uint8_t d2_pin;
    uint8_t d3_port;
    uint8_t d3_pin;
    uint8_t ck_port;
    uint8_t ck_pin;
    uint8_t cmd_port;
    uint8_t cmd_pin;
    uint8_t phase;
    uint32_t capacity;
    uint32_t block_size;
    uint32_t block_count;
    uint32_t max_bus_clock_frequency;
    uint8_t csd_version;
    uint16_t relative_card_address;
    uint8_t manufacturer_id;
    uint16_t oem_id;
    char product_name[6];
    uint8_t product_revision;
    uint32_t serial_number;
    uint16_t manufacturing_date;
    uint8_t version;      // 2 or 1
    bool_t high_capacity; // 1 for SDHC/SDXC card
} transport_sdio_properties_t;
/* End of autogenerated OD types */

struct transport_sdio {
    actor_t *actor;
    transport_sdio_properties_t *properties;
    uint32_t address;
    uint32_t *source_clock;
    uint16_t reset;
    uint16_t peripheral_clock;
    uint8_t irq;
    app_job_t job;
};

extern actor_class_t transport_sdio_class;

/* Start of autogenerated OD accessors */
typedef enum transport_sdio_properties_properties {
    TRANSPORT_SDIO_DMA_UNIT = 0x01,
    TRANSPORT_SDIO_DMA_STREAM = 0x02,
    TRANSPORT_SDIO_DMA_CHANNEL = 0x03,
    TRANSPORT_SDIO_AF = 0x04,
    TRANSPORT_SDIO_D0_PORT = 0x05,
    TRANSPORT_SDIO_D0_PIN = 0x06,
    TRANSPORT_SDIO_D1_PORT = 0x07,
    TRANSPORT_SDIO_D1_PIN = 0x08,
    TRANSPORT_SDIO_D2_PORT = 0x09,
    TRANSPORT_SDIO_D2_PIN = 0x0A,
    TRANSPORT_SDIO_D3_PORT = 0x0B,
    TRANSPORT_SDIO_D3_PIN = 0x0C,
    TRANSPORT_SDIO_CK_PORT = 0x0D,
    TRANSPORT_SDIO_CK_PIN = 0x0E,
    TRANSPORT_SDIO_CMD_PORT = 0x0F,
    TRANSPORT_SDIO_CMD_PIN = 0x10,
    TRANSPORT_SDIO_PHASE = 0x11,
    TRANSPORT_SDIO_CAPACITY = 0x12,
    TRANSPORT_SDIO_BLOCK_SIZE = 0x13,
    TRANSPORT_SDIO_BLOCK_COUNT = 0x14,
    TRANSPORT_SDIO_MAX_BUS_CLOCK_FREQUENCY = 0x15,
    TRANSPORT_SDIO_CSD_VERSION = 0x16,
    TRANSPORT_SDIO_RELATIVE_CARD_ADDRESS = 0x17,
    TRANSPORT_SDIO_MANUFACTURER_ID = 0x18,
    TRANSPORT_SDIO_OEM_ID = 0x19,
    TRANSPORT_SDIO_PRODUCT_NAME = 0x1A,
    TRANSPORT_SDIO_PRODUCT_REVISION = 0x1B,
    TRANSPORT_SDIO_SERIAL_NUMBER = 0x1C,
    TRANSPORT_SDIO_MANUFACTURING_DATE = 0x1D,
    TRANSPORT_SDIO_VERSION = 0x1E,
    TRANSPORT_SDIO_HIGH_CAPACITY = 0x1F
} transport_sdio_properties_properties_t;

/* 0x62A011: null */
#define transport_sdio_set_phase(sdio, value)                                                                                              \
    actor_set_property_numeric(sdio->actor, TRANSPORT_SDIO_PHASE, (uint32_t)(value), sizeof(uint8_t))
#define transport_sdio_get_phase(sdio) *((uint8_t *) actor_get_property_pointer(sdio->actor, TRANSPORT_SDIO_PHASE)
/* 0x62A012: null */
#define transport_sdio_set_capacity(sdio, value)                                                                                           \
    actor_set_property_numeric(sdio->actor, TRANSPORT_SDIO_CAPACITY, (uint32_t)(value), sizeof(uint32_t))
#define transport_sdio_get_capacity(sdio) *((uint32_t *) actor_get_property_pointer(sdio->actor, TRANSPORT_SDIO_CAPACITY)
/* 0x62A013: null */
#define transport_sdio_set_block_size(sdio, value)                                                                                         \
    actor_set_property_numeric(sdio->actor, TRANSPORT_SDIO_BLOCK_SIZE, (uint32_t)(value), sizeof(uint32_t))
#define transport_sdio_get_block_size(sdio) *((uint32_t *) actor_get_property_pointer(sdio->actor, TRANSPORT_SDIO_BLOCK_SIZE)
/* 0x62A014: null */
#define transport_sdio_set_block_count(sdio, value)                                                                                        \
    actor_set_property_numeric(sdio->actor, TRANSPORT_SDIO_BLOCK_COUNT, (uint32_t)(value), sizeof(uint32_t))
#define transport_sdio_get_block_count(sdio) *((uint32_t *) actor_get_property_pointer(sdio->actor, TRANSPORT_SDIO_BLOCK_COUNT)
/* 0x62A015: null */
#define transport_sdio_set_max_bus_clock_frequency(sdio, value)                                                                            \
    actor_set_property_numeric(sdio->actor, TRANSPORT_SDIO_MAX_BUS_CLOCK_FREQUENCY, (uint32_t)(value), sizeof(uint32_t))
#define transport_sdio_get_max_bus_clock_frequency(sdio) *((uint32_t *) actor_get_property_pointer(sdio->actor, TRANSPORT_SDIO_MAX_BUS_CLOCK_FREQUENCY)
/* 0x62A016: null */
#define transport_sdio_set_csd_version(sdio, value)                                                                                        \
    actor_set_property_numeric(sdio->actor, TRANSPORT_SDIO_CSD_VERSION, (uint32_t)(value), sizeof(uint8_t))
#define transport_sdio_get_csd_version(sdio) *((uint8_t *) actor_get_property_pointer(sdio->actor, TRANSPORT_SDIO_CSD_VERSION)
/* 0x62A017: null */
#define transport_sdio_set_relative_card_address(sdio, value)                                                                              \
    actor_set_property_numeric(sdio->actor, TRANSPORT_SDIO_RELATIVE_CARD_ADDRESS, (uint32_t)(value), sizeof(uint16_t))
#define transport_sdio_get_relative_card_address(sdio) *((uint16_t *) actor_get_property_pointer(sdio->actor, TRANSPORT_SDIO_RELATIVE_CARD_ADDRESS)
/* 0x62A018: null */
#define transport_sdio_set_manufacturer_id(sdio, value)                                                                                    \
    actor_set_property_numeric(sdio->actor, TRANSPORT_SDIO_MANUFACTURER_ID, (uint32_t)(value), sizeof(uint8_t))
#define transport_sdio_get_manufacturer_id(sdio) *((uint8_t *) actor_get_property_pointer(sdio->actor, TRANSPORT_SDIO_MANUFACTURER_ID)
/* 0x62A019: null */
#define transport_sdio_set_oem_id(sdio, value)                                                                                             \
    actor_set_property_numeric(sdio->actor, TRANSPORT_SDIO_OEM_ID, (uint32_t)(value), sizeof(uint16_t))
#define transport_sdio_get_oem_id(sdio) *((uint16_t *) actor_get_property_pointer(sdio->actor, TRANSPORT_SDIO_OEM_ID)
/* 0x62A01A: null */
#define transport_sdio_set_product_name(sdio, value, size) actor_set_property_string(sdio->actor, TRANSPORT_SDIO_PRODUCT_NAME, value, size)
#define transport_sdio_get_product_name(sdio) *((char *) actor_get_property_pointer(sdio->actor, TRANSPORT_SDIO_PRODUCT_NAME)
/* 0x62A01B: null */
#define transport_sdio_set_product_revision(sdio, value)                                                                                   \
    actor_set_property_numeric(sdio->actor, TRANSPORT_SDIO_PRODUCT_REVISION, (uint32_t)(value), sizeof(uint8_t))
#define transport_sdio_get_product_revision(sdio) *((uint8_t *) actor_get_property_pointer(sdio->actor, TRANSPORT_SDIO_PRODUCT_REVISION)
/* 0x62A01C: null */
#define transport_sdio_set_serial_number(sdio, value)                                                                                      \
    actor_set_property_numeric(sdio->actor, TRANSPORT_SDIO_SERIAL_NUMBER, (uint32_t)(value), sizeof(uint32_t))
#define transport_sdio_get_serial_number(sdio) *((uint32_t *) actor_get_property_pointer(sdio->actor, TRANSPORT_SDIO_SERIAL_NUMBER)
/* 0x62A01D: null */
#define transport_sdio_set_manufacturing_date(sdio, value)                                                                                 \
    actor_set_property_numeric(sdio->actor, TRANSPORT_SDIO_MANUFACTURING_DATE, (uint32_t)(value), sizeof(uint16_t))
#define transport_sdio_get_manufacturing_date(sdio) *((uint16_t *) actor_get_property_pointer(sdio->actor, TRANSPORT_SDIO_MANUFACTURING_DATE)
/* 0x62A01E: 2 or 1 */
#define transport_sdio_set_version(sdio, value)                                                                                            \
    actor_set_property_numeric(sdio->actor, TRANSPORT_SDIO_VERSION, (uint32_t)(value), sizeof(uint8_t))
#define transport_sdio_get_version(sdio) *((uint8_t *) actor_get_property_pointer(sdio->actor, TRANSPORT_SDIO_VERSION)
/* 0x62A01F: 1 for SDHC/SDXC card */
#define transport_sdio_set_high_capacity(sdio, value)                                                                                      \
    actor_set_property_numeric(sdio->actor, TRANSPORT_SDIO_HIGH_CAPACITY, (uint32_t)(value), sizeof(bool_t))
#define transport_sdio_get_high_capacity(sdio) *((bool_t *) actor_get_property_pointer(sdio->actor, TRANSPORT_SDIO_HIGH_CAPACITY)
/* End of autogenerated OD accessors */

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif